using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class ArtefactStatistics
{
    // This is the genome ID generated by SharpNEAT. Can be used to identify which 
    public uint genomeID;
    public uint generation;
    public Color color;

    public List<uint> parents;
    public List<string> usersInteracted;

    public int distanceTraveledSinceInception;
    public int numberOfSeedsReplanted;

    public ArtefactStatistics(uint genomeID, uint generation)
    {
        this.genomeID = genomeID;
        this.generation = generation;
        parents = new List<uint>();
        usersInteracted = new List<string>();
    }
}
